# Debug configuration
# https://pythonhosted.org/Flask-Environments
# Set FLASK_ENV to the environment (defult: DEVELOPMENT)

COMMON: &common
  APP_NAME: 'Flask Demo'

  DEBUG: False
  PROD: False

  PORT: 5000

  LOG_LEVEL: DEBUG

#
# Dev: meaning local workstation (not on Docker)
#

DEVELOPMENT: &development
  <<: *common

  DEBUG: True
  LOG_FILE: ../../../app.log

#
# Prod
#

PRODUCTION: &production
  <<: *common

  PROD: True
  LOG_FILE: /home/demo/app.log
