# Debug configuration
# https://pythonhosted.org/Flask-Environments
# Set FLASK_ENV to the environment (defult: DEVELOPMENT)

COMMON: &common
  APP_NAME: 'Flask Demo'

  DEBUG: False
  PROD: False

  HOST: 0.0.0.0     # NOTE: Important for nginx config.
  PORT: 5000

  LOG_CONFIG: config/logging.yml

#
# Dev: meaning local workstation (not on Docker)
#

DEVELOPMENT: &development
  <<: *common

  DEBUG: True

#
# Prod
#

PRODUCTION: &production
  <<: *common

  PROD: True
